import pandas as pd
from fpdf import FPDF
from datetime import date

# Load Data
df = pd.read_csv("data.csv")

# Basic Analysis
total_score = df['Score'].sum()
average_score = df['Score'].mean()

# PDF Report Generation
class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "Automated Report", ln=True, align='C')
        self.set_font("Arial", "", 12)
        self.cell(0, 10, "Generated by CodTech Internship Project", ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 10)
        self.cell(0, 10, f"Page {self.page_no()}", align='C')

pdf = PDF()
pdf.add_page()

# Title
pdf.set_font("Arial", "B", 14)
pdf.cell(0, 10, "Data Analysis Report", ln=True)

# Add Table Header
pdf.set_font("Arial", "B", 12)
pdf.cell(60, 10, "Name", 1)
pdf.cell(40, 10, "Score", 1)
pdf.ln()

# Add Table Data
pdf.set_font("Arial", "", 12)
for index, row in df.iterrows():
    pdf.cell(60, 10, row["Name"], 1)
    pdf.cell(40, 10, str(row["Score"]), 1)
    pdf.ln()

# Summary
pdf.ln(5)
pdf.set_font("Arial", "B", 12)
pdf.cell(0, 10, f"Total Score: {total_score}", ln=True)
pdf.cell(0, 10, f"Average Score: {average_score:.2f}", ln=True)
pdf.ln(5)

# Completion Note
pdf.set_font("Arial", "I", 11)
pdf.multi_cell(0, 10, f"Completion Certificate will be issued on your internship end date.\n\nGenerated on: {date.today()}")

# Save Report
pdf.output("report.pdf")

print("PDF report generated successfully as 'report.pdf'")
